baseURL = 'https://castlelorestudios.com/'
languageCode = 'en-us'
title = 'Castlelore Studios'
theme = "hugo-split-theme"

copyright = '© 2025 Castlelore Studios LLC'
enableEmoji = true
enableRobotsTXT = true

logo = "images/LogoWhite.png"
favicon = "images/favicon.ico"

[params.visual.video]
  enable = true
  mute = true
  file = "videos/background.mp4"
  youtubeId = "eSga-3FKrpk"

[params.custom.css]
enable = true

[params]
  author = "Castlelore Studios LLC"
  description = "A visual novel studio creating dark, psychological horror games."
  shareImage = "images/LogoWhite.png"
  twitterHandle = "CastleloreSt"
  facebookPage = "CastleloreStudios"
  instagramHandle = "castlelore_studios"
  discordInvite = "https://discord.gg/4a2b6Z5"
  licensed = "true"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Demo"
    url = "/demo"
    weight = 20
  [[menu.main]]
    name = "Wiki"
    url = "/wiki"
    weight = 30
