baseURL = 'https://castlelorestudios.com/'
languageCode = 'en-us'
title = 'Castlelore Studios'
theme = "hugo-split-theme"

copyright = '© 2025 Castlelore Studios LLC'
enableEmoji = true
enableRobotsTXT = true

custom_css = ["css/custom.css"]

logo = "images/LogoWhite.png"
favicon = "images/favicon.ico"

[params.visual.video]
  enable = true
  mute = true
  file = "videos/background.mp4"
  youtubeId = "eSga-3FKrpk"

[params.custom.css]
  enable = true

[params]
  author = "Castlelore Studios LLC"
  description = "A visual novel studio creating dark, psychological horror games."
  shareImage = "images/LogoWhite.png"
  twitterHandle = "CastleloreSt"
  facebookPage = "CastleloreStudios"
  instagramHandle = "castlelore_studios"
  discordInvite = "https://discord.gg/4a2b6Z5"

[[params.links]]
  [params.links.list1]
    heading = "Connect"

    [[params.links.list1.link]]
      text = "Discord"
      url = "https://discord.com/invite/nZZrUMXUsS"
      new_tab = true # new tab

